services:
  # Background worker service for the Telegram bot
  - type: worker
    name: medusa-course-bot
    plan: starter
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/greatautomate/courseX  # Update with your actual repo
    branch: main
    autoDeploy: false
    dockerCommand: python3 main.py
    envVars:
      # Required Telegram Bot Configuration
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false

      # Optional Configuration
      - key: OWNER
        value: "7527795504"  # Set to 0 by default, configure in dashboard
      - key: CREDIT
        value: "ミ★ medusaXD ★彡"
      - key: AUTH_USERS
        value: "7527795504"  # Comma-separated list of authorized user IDs

      # Bot Configuration (no server needed)
      - key: WEBHOOK
        value: "false"

      # API Tokens and URLs
      - key: API_URL
        value: "http://master-api-v3.vercel.app/"
      - key: API_TOKEN
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzkxOTMzNDE5NSIsInRnX3VzZXJuYW1lIjoi4p61IFtvZmZsaW5lXSIsImlhdCI6MTczODY5MjA3N30.SXzZ1MZcvMp5sGESj0hBKSghhxJ3k1GTWoBUbivUe1I"
      - key: TOKEN_CP
        value: "eyJjb3Vyc2VJZCI6IjQ1NjY4NyIsInR1dG9ySWQiOm51bGwsIm9yZ0lkIjo0ODA2MTksImNhdGVnb3J5SWQiOm51bGx9r"
      - key: ADDA_TOKEN
        value: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkcGthNTQ3MEBnbWFpbC5jb20iLCJhdWQiOiIxNzg2OTYwNSIsImlhdCI6MTc0NDk0NDQ2NCwiaXNzIjoiYWRkYTI0Ny5jb20iLCJuYW1lIjoiZHBrYSIsImVtYWlsIjoiZHBrYTU0NzBAZ21haWwuY29tIiwicGhvbmUiOiI3MzUyNDA0MTc2IiwidXNlcklkIjoiYWRkYS52MS41NzMyNmRmODVkZDkxZDRiNDkxN2FiZDExN2IwN2ZjOCIsImxvZ2luQXBpVmVyc2lvbiI6MX0.0QOuYFMkCEdVmwMVIPeETa6Kxr70zEslWOIAfC_ylhbku76nDcaBoNVvqN4HivWNwlyT0jkUKjWxZ8AbdorMLg"

      # Image URLs
      - key: PHOTO_LOGO
        value: "https://tinypic.host/images/2025/02/07/DeWatermark.ai_1738952933236-1.png"
      - key: PHOTO_YT
        value: "https://tinypic.host/images/2025/03/18/YouTube-Logo.wine.png"
      - key: PHOTO_CP
        value: "https://tinypic.host/images/2025/03/28/IMG_20250328_133126.jpg"
      - key: PHOTO_ZIP
        value: "https://envs.sh/cD_.jpg"

      # File paths
      - key: COOKIES_FILE_PATH
        value: "youtube_cookies.txt"
      - key: TOKENS_FILE
        value: "dynamic_tokens.json"
